# config-test-frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat-frontend-test
  template:
    metadata:
      labels:
        app: cat-frontend-test
    spec:
      containers:
      - name: frontend
        image: localhost:32000/frontend:k8s          # built locally: `docker build -t localhost:32000/frontend:k8s .`
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5000
          hostPort: 5001             # so you can hit localhost:5001
        env:
        - name: BACKEND_URL
          value: "http://localhost:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: cat-frontend-test
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 30080               # pick an unused port in 30000-32767
