# config-frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: localhost:32000/frontend:k8s
        env:
        - name: ADD_CAT_URL
          value: "http://add-cat:5000"
        - name: WEATHER_URL
          value: "http://weather:5000"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80                                 # external port
    targetPort: 5000                         # container port
    protocol: TCP
