apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployback
  labels:
    app: deployback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployback
  template:
    metadata:
      labels:
        app: deployback
    spec:
      containers:
      - name: deployback
        image: localhost:32000/backside:k8s

---

apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  type: NodePort
  selector:
    app: deployback
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30080



