apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-upper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: to-upper
  template:
    metadata:
      labels:
        app: to-upper
    spec:
      containers:
      - name: to-upper-container
        image: localhost:32000/to-upper:k8s

---

apiVersion: v1
kind: Service
metadata:
  name: to-upper-service
spec:
  type: NodePort
  selector:
    app: to-upper
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30081

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: to-upper-restart
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: restart
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - |
              kubectl rollout restart deployment/to-upper-deployment
          restartPolicy: OnFailure
