apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokequiz-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokequiz
  template:
    metadata:
      labels:
        app: pokequiz
    spec:
      containers:
      - name: pokequiz-container
        image: localhost:32000/pokequiz:k8s

---

apiVersion: v1
kind: Service
metadata:
  name: pokequiz-service
spec:
  type: NodePort
  selector:
    app: pokequiz
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30081
