# config-backend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat-backend
  template:
    metadata:
      labels:
        app: cat-backend
    spec:
      containers:
      - name: backend
        image: localhost:32000/add-cat-service:k8s      # ← replace with your actual image
        resources:
          limits:
            nvidia.com/gpu: 1                 # request 1 GPU for the inpainting model
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP                            # internal-only
  selector:
    app: cat-backend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
